name: Deploy App to EB

on:
  push:
    branches:
      - main
      - oauth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build application
        run: |
          mvn clean package -DskipTests

      - name: Make postdeploy script executable
        run: chmod +x .platform/hooks/postdeploy/01_setup_ssl.sh

      - name: Set AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "booking-app"
          environment_name: "Booking-app-env"
          region: "us-east-1"
          version_label: "deploy-${{ github.run_number }}-${{ github.sha }}"
          deployment_package: "target/localservice-api-0.0.1-SNAPSHOT.jar"
          use_existing_version_if_available: true
