name: Deploy App to EB

on:
  push:
    branches:
      - main
      - ticket-37

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build application
        run: mvn clean package

      - name: Verify JAR exists
        run: |
          if [ ! -f target/localservice-api-0.0.1-SNAPSHOT.jar ]; then
            echo "Build failed: JAR file not found!"
            exit 1
          fi

      - name: Create environment variables JSON
        run: |
          cat <<EOF > eb-options.json
          [
            {"Namespace": "aws:elasticbeanstalk:application:environment", "OptionName": "DB_URL", "Value": "${{ secrets.DB_URL }}"},
            {"Namespace": "aws:elasticbeanstalk:application:environment", "OptionName": "DB_PASSWORD", "Value": "${{ secrets.DB_PASSWORD }}"},
            {"Namespace": "aws:elasticbeanstalk:application:environment", "OptionName": "SMTP_USER", "Value": "${{ secrets.SMTP_USER }}"},
            {"Namespace": "aws:elasticbeanstalk:application:environment", "OptionName": "SMTP_PWD", "Value": "${{ secrets.SMTP_PWD }}"}
          ]
          EOF

      - name: Set environment variables for Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --region "us-east-1" \
            --environment-name "Booking-app-env" \
            --option-settings file://eb-options.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "booking-app"
          environment_name: "Booking-app-env"
          region: "us-east-1"
          version_label: "deploy-${{ github.run_number }}-${{ github.sha }}"
          deployment_package: "target/localservice-api-0.0.1-SNAPSHOT.jar"
          use_existing_version_if_available: true
